apiVersion: v1
kind: Service
metadata:
  name: appgateflask-service
  labels:
    run: appgateflask
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32739
  type: NodePort
  selector:
    app: appgateflask
